### ISSUE TITLE
Frontend: catch 404 backend error

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#340]
* **I'm submitting a ...**
  * feature request

* **What is the current behavior?**
When I enter a URL that triggers a backend call returning a 404 error, I see an infinite loading spinner.

* **What is the expected behavior?**
I should see an error page "404 - Not found".

* **What is the motivation / use case for changing the behavior?**
Better user experience.

![selection_070](https://user-images.githubusercontent.com/2110676/31638965-a8083cdc-b2d6-11e7-8494-5d98cbb07e93.png)

 
* **If you want to request a whole new feature, please provide a user story (otherwise delete):**
  * As a `user`
  * I want `to see a 404 error page for a broadcast that does not exist (yet/anymore)`
  * So that `I understand what's the problem`

**Comment by apravink** [comment]
I'd like to take a shot at this

**Comment by sigu** [comment]
This was solved also on my first PR

**Comment by roschaefer** [comment]
@sigu No, that's a different issue. You closed https://github.com/roschaefer/rundfunk-mitbestimmen/issues/348.

You can visit https://rundfunk-mitbestimmen.de/broadcast/42 to verify that this error still exists.
